version: '3'
services:
  web:
    image: nginx:alpine
    ports:
      - "8088:80"
    volumes:
      - .:/app
      - ./config/site.dev.conf:/etc/nginx/conf.d/default.conf
    working_dir: /app

  php:
    image: php:7-fpm
    volumes:
      - .:/app
    working_dir: /app
    command: ["sh", "-c", "docker-php-ext-install pdo_mysql && php-fpm"]

  mysql.database:
    image: mysql:5.7
    volumes:
      - ./.data-storage:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: api
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "33061:3306"
