version: '3'
services:
  web:
    image: nginx:alpine
    ports:
      - "8088:80"
    volumes:
      - .:/app
      - ./config/site.dev.conf:/etc/nginx/conf.d/default.conf

  php:
    image: php:7-fpm
    volumes:
      - .:/app

